---
# tasks file for install terraform on Mac osx system

- name: Darwin | Find all versions of Terraform
  uri:
    url: https://releases.hashicorp.com/terraform/index.json
    return_content: yes
  register: terraform_index

- name: Darwin | Finds the latest Terraform version when latest var is define
  set_fact:
    terraform_version: "{{ (terraform_index.content | from_json).versions | reject('search','-') | list | sort_versions | last }}"
  when: terraform_version == 'latest'

# This task avoids downloading Terraform every time
- name: Darwin | Check if terraform is present with the right version
  command: "{{ terraform_path }}/terraform -version"
  register: terraform_installed_version
  ignore_errors: yes
  changed_when: false
  failed_when: false

- name: Darwin | Install Terraform
  unarchive:
    src: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_darwin_amd64.zip"
    dest: "{{ terraform_path }}"
    remote_src: yes
  when: terraform_version not in terraform_installed_version.stdout | default('')
