---
# tasks file for install terraform on openbsd system

- name: OpenBSD | Find all versions of Terraform
  uri:
    url: https://releases.hashicorp.com/terraform/index.json
    return_content: yes
  register: terraform_index
  when: terraform_version == 'latest'

- name: OpenBSD | Finds the latest Terraform version when latest var is define
  set_fact:
    terraform_version_to_install: "{{ (terraform_index.content | from_json).versions | reject('search','-') | list | sort_versions | last }}"
  when: terraform_version == 'latest'

- name: OpenBSD | Use the specified Terraform version when latest var is not define
  set_fact:
    terraform_version_to_install: "{{ terraform_version }}"
  when: terraform_version != 'latest'

# This task avoids downloading Terraform every time
- name: OpenBSD | Check if Terraform is present with the right version
  command: "{{ terraform_path }}/terraform -version"
  register: terraform_installed_version
  ignore_errors: yes
  changed_when: false
  failed_when: false

- name: OpenBSD | Install Terraform
  unarchive:
    src: "https://releases.hashicorp.com/terraform/{{ terraform_version_to_install }}/terraform_{{ terraform_version_to_install }}_openbsd_amd64.zip"
    dest: "{{ terraform_path }}"
    remote_src: yes
  when: terraform_version_to_install not in terraform_installed_version.stdout_lines | default('empty') | first
